version: '3'


services:
  mariadb:
    container_name: ${MARIADB_CONTAINER_NAME}
    image: ${MARIADB_IMAGE}
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_USER_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_ROOT_HOST: '%'
    ports:
      - '${MARIADB_PORT}:${DATABASE_PORT}'
    # volumes:
    #   - './mariadb:/var/lib/mysql'
    #   - ./migration:/docker-entrypoint-initdb.d/

